# Generated by Django 3.1.7 on 2021-03-02 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
